language: python
cache: pip
dist: trusty

# Environment variables
env:
  TEST_QT=false

# Test environments
matrix:
  include:
   - env: TOXENV=py34
     python: 3.4
   #- env: TOXENV=py35
   #  python: 3.5
   #- env: TOXENV=py36
   #  python: 3.6

# Prepare installation
addons:
  apt:
    sources:
      sdfsd


before_install:
  - sudo apt-get update
  - sudo apt-get -qq install python3-pyqt5 python3-pyqt5.qsci

# Package installation
install:
  - apt-get install python3-pyqt5
  - pip install tox codecov

# Run tests
script:
  - tox

# Register code coverage in coveralls
after_success:
  - codecov